create table if not exists projects(
    id integer PRIMARY KEY generated BY DEFAULT AS IDENTITY,
    name TEXT not null check (name <> ''),
    priority integer not null,
    description text,
    deliverdate date not null
);


create table if not exists tasks(
    id integer primary key generated BY DEFAULT AS IDENTITY,
    name TEXT not null check (name <> ''),
    done boolean 
    project_id integer references projects(id)
);